/**
 * Icon registry for EduVanta.
 * All Lucide icon names used in navigation.ts and the app shell must be listed here.
 * Components resolve icon strings via getIcon(name) instead of importing icons directly.
 */
import type { LucideIcon } from "lucide-react";
import {
  AlertCircle,
  ArrowDownCircle,
  ArrowLeftRight,
  ArrowUpCircle,
  Award,
  Banknote,
  BarChart3,
  Bell,
  BookMarked,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CalendarDays,
  CalendarOff,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ClipboardCheck,
  Coins,
  CreditCard,
  DoorOpen,
  FileText,
  FolderOpen,
  GraduationCap,
  HelpCircle,
  Languages,
  Layers,
  LayoutDashboard,
  Library,
  ListFilter,
  ListOrdered,
  LogOut,
  Menu,
  MessageSquare,
  Monitor,
  Moon,
  Percent,
  RefreshCw,
  Search,
  Settings,
  ShieldCheck,
  Star,
  Sun,
  Tag,
  TrendingDown,
  TrendingUp,
  User,
  UserCheck,
  UserCircle,
  UserCog,
  UserPlus,
  UserX,
  Users,
  X,
} from "lucide-react";

export type { LucideIcon };

export const iconRegistry: Record<string, LucideIcon> = {
  AlertCircle,
  ArrowDownCircle,
  ArrowLeftRight,
  ArrowUpCircle,
  Award,
  Banknote,
  BarChart3,
  Bell,
  BookMarked,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CalendarDays,
  CalendarOff,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ClipboardCheck,
  Coins,
  CreditCard,
  DoorOpen,
  FileText,
  FolderOpen,
  GraduationCap,
  HelpCircle,
  Languages,
  Layers,
  LayoutDashboard,
  Library,
  ListFilter,
  ListOrdered,
  LogOut,
  Menu,
  MessageSquare,
  Monitor,
  Moon,
  Percent,
  RefreshCw,
  Search,
  Settings,
  ShieldCheck,
  Star,
  Sun,
  Tag,
  TrendingDown,
  TrendingUp,
  User,
  UserCheck,
  UserCircle,
  UserCog,
  UserPlus,
  UserX,
  Users,
  X,
};

/**
 * Look up a Lucide icon component by name string.
 * Falls back to HelpCircle if the name is not found in the registry.
 */
export function getIcon(name: string): LucideIcon {
  return iconRegistry[name] ?? HelpCircle;
}
